export const Items = {
  S001: {
    brand: 'Parle 20-20',
    id: 'G2',
    image: 'https://iili.io/JjPeTl.jpg',
    price: '5',
    type: 'Biscuits',
    unit: 'gm',
    weight: '45',
  },
  S002: {
    brand: 'Parle Krackjack',
    id: 'G3',
    image: 'https://iili.io/JjQE9s.jpg',
    price: '5',
    type: 'Biscuits',
    unit: 'gm',
    weight: '37.8',
  },
  S003: {
    brand: 'Parle Happy Happy ',
    id: 'G4',
    image: 'https://iili.io/JjQ6iB.jpg',
    price: '5',
    type: 'Biscuits',
    unit: 'gm',
    weight: '40',
  },
  S004: {
    brand: 'Parle Hide & Seek Bourbon',
    id: 'G5',
    image: 'https://iili.io/JjQsl1.jpg',
    price: '10',
    type: 'Biscuits',
    unit: 'gm',
    weight: '50',
  },
  S005: {
    brand: ' Britannia Good Day',
    id: 'G6',
    imagae: 'https://iili.io/JjQDOJ.jpg',
    price: '5',
    type: 'Biscuits',
    unit: 'gm',
    weight: '53',
  },
  S006: {
    brand: ' Britannia Marie Gold',
    id: 'G7',
    imagae: 'https://iili.io/JjZ2UX.jpg ',
    price: '10',
    type: 'Biscuits',
    unit: 'gm',
    weight: '80',
  },
  S007: {
    brand: 'Patanjali Dant Kanti',
    id: 'T4',
    image: 'https://iili.io/JjtW4S.jpg',
    price: '10',
    type: 'Toothpaste',
    unit: 'gm',
    weight: '10',
  },
  S008: {
    brand: 'CloseUp Everfresh',
    id: 'T3',
    image: 'https://iili.io/JjtuBp.jpg',
    price: '10',
    type: 'Toothpaste',
    unit: 'gm',
    weight: '22',
  },
  S009: {
    brand: 'Colgate Max Fresh',
    id: 'T2',
    image: 'https://iili.io/JjtxTJ.jpg',
    price: '10',
    type: 'Toothpaste',
    unit: 'gm',
    weight: '24',
  },
  S010: {
    brand: 'Colgate',
    id: 'T1',
    image: 'https://iili.io/JjtJhx.jpg ',
    price: '10',
    type: 'Toothpaste',
    unit: 'gm',
    weight: '19',
  },
  S011: {
    brand: 'Maggi ',
    id: 'N1',
    image: 'https://iili.io/JjtLua.jpg',
    price: '5',
    type: 'Noodles',
    unit: 'gm',
    weight: '35',
  },
  S012: {
    brand: 'Maggi ',
    id: 'N2',
    image: 'https://iili.io/JjtLua.jpg',
    price: '10 ',
    type: 'Noodles',
    unit: 'gm',
    weight: '70',
  },
  S013: {
    brand: 'Sunfeast Yippee',
    id: 'N3',
    image: 'https://iili.io/JjtbGp.jpg',
    price: '10 ',
    type: 'Noodles',
    unit: 'gm',
    weight: '60',
  },
  S014: {
    brand: 'Sunfeast Yippee',
    id: 'N4',
    image: 'https://iili.io/JjtbGp.jpg',
    price: '5 ',
    type: 'Noodles',
    unit: 'gm',
    weight: '30',
  },
  S015: {
    brand: 'Lifebuoy',
    id: 'S1',
    image: 'https://iili.io/JjD3wG.jpg',
    price: '10',
    type: 'Soap ',
    unit: 'gm',
    weight: '120',
  },
  S016: {
    brand: 'Dettol',
    id: 'S2',
    image: 'https://iili.io/JjDYPV.jpg ',
    price: '10',
    type: 'Soap ',
    unit: 'gm',
    weight: '45',
  },
  S017: {
    brand: 'Lux',
    id: 'S3',
    image: 'https://iili.io/JjDlcP.jpg ',
    price: '10',
    type: 'Soap ',
    unit: 'gm',
    weight: '45',
  },
  S018: {
    brand: 'Dove',
    id: 'S4',
    image: 'https://iili.io/Jjpll2.jpg',
    price: '10',
    type: 'Soap ',
    unit: 'gm',
    weight: '28',
  },
  S019: {
    brand: 'Margo Neem',
    id: 'S5',
    image: 'https://iili.io/JjpXob.jpg',
    price: '10',
    type: 'Soap ',
    unit: 'gm',
    weight: '30',
  },
  S020: {
    brand: 'Goorej No 1',
    id: 'S6',
    image: 'https://iili.io/JwCpvs.jpg',
    price: '10',
    type: 'Soap ',
    unit: 'gm',
    weight: '30',
  },
  S021: {
    brand: 'Goorej No 1',
    id: 'S6',
    image: 'https://iili.io/JwnJj4.jpg',
    price: '20',
    type: 'Soap ',
    unit: 'gm',
    weight: '70',
  },
  S022: {
    brand: 'Shakar',
    id: 'A1',
    image: 'https://iili.io/Jwn3n2.jpg',
    price: '38',
    type: 'Sugar ',
    unit: 'Kg',
    weight: '1',
  },
  S023: {
    brand: 'Shakar',
    id: 'A2',
    image: 'https://iili.io/Jwnnyb.webp',
    price: '18',
    type: 'Sugar ',
    unit: 'Gm',
    weight: '500',
  },
  S024: {
    brand: 'Mahakosh Refined Oil',
    id: 'O1',
    image: 'https://iili.io/JwnR6P.jpg',
    price: '100',
    type: 'Oil ',
    unit: 'Lt',
    weight: '1',
  },
  S025: {
    brand: 'Kriti Refined Soyabeen Oil',
    id: 'O2',
    image: 'https://iili.io/Jwn7F1.jpg',
    price: '100',
    type: 'Oil ',
    unit: 'Lt',
    weight: '1',
  },
  S025: {
    brand: 'Khandwa Fresh Soyabeen Oil',
    id: 'O3',
    image: 'https://iili.io/Jwn0AJ.jpg',
    price: '100',
    type: 'Oil ',
    unit: 'Lt',
    weight: '1',
  },
  S027: {
    brand: 'Clinic Plus',
    id: 'B1',
    image: 'https://iili.io/Jwn1wv.jpg',
    price: '1',
    type: 'Shampoo',
    unit: 'Ml',
    weight: '1.6',
  },
  S028: {
    brand: 'Head & Shoulders ',
    id: 'B2',
    image: 'https://iili.io/JwnWPI.jpg',
    price: '2',
    type: 'Shampoo',
    unit: 'ML',
    weight: '3',
  },
  S029: {
    brand: 'Dove Intense Repair Twin Pack ',
    id: 'B3',
    image: 'https://iili.io/JwoMOb.jpg',
    price: '5',
    type: 'Shampoo',
    unit: 'ML',
    weight: '6',
  },
};
